# 服务端口
server:
  port: 8008
spring:
  application:
    # 服务名
    name: service-statistics
  profiles:
    # 环境设置
    active: dev
  # mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_college?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: xhn021019
  # 定义统一返回的json时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # 配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml

