server:
  port: 8004
spring:
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_college?useSSL=false&serverTimezone=GMT%2B8
    username: yourName
    password: yourPwd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    timeout: 180000ms # 连接超时时间（毫秒）
    lettuce: # 使用lettuce客户端，提供了更多的自定义配置
      pool:
        max-active: 20 # 最大连接数
        max-wait: -1 # 最大阻塞等待时间，-1表示一直等待
        max-idle: 5 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
    password: yourPwd

mybatis-plus:
  mapper-locations: classpath:com/kevin/cms/mapper/xml/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
