server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大总上传的数据大小
      max-request-size: 1024MB
      # 最大上传的单个文件大小
      max-file-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 阿里云vod
aliyun:
  vod:
    file:
      keyid: LTAI5tDzWag6iFewhLyVRGQS
      keysecret: u3NrQmkivdtFzsRftaJHU5qGq6DnNW
